config/routes.rb
Rails.application.routes.draw do
  resources :breads
  resources :pizzas

end

app/models/bread.rb
class Bread < ActiveRecord::Base
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
	validates_presence_of :name, :description, :price, :photo
	validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breads_controller.rb
class BreadsController < ApplicationController
  before_action :set_bread, only: [:show, :edit, :update, :destroy]

  # GET /breads
  # GET /breads.json
  def index
    @breads = Bread.all
  end

  # GET /breads/1
  # GET /breads/1.json
  def show
  end

  # GET /breads/new
  def new
    @bread = Bread.new
  end

  # GET /breads/1/edit
  def edit
  end

  # POST /breads
  # POST /breads.json
  def create
    @bread = Bread.new(bread_params)

    respond_to do |format|
      if @bread.save
        format.html { redirect_to @bread, notice: 'Bread was successfully created.' }
        format.json { render :show, status: :created, location: @bread }
      else
        format.html { render :new }
        format.json { render json: @bread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breads/1
  # PATCH/PUT /breads/1.json
  def update
    respond_to do |format|
      if @bread.update(bread_params)
        format.html { redirect_to @bread, notice: 'Bread was successfully updated.' }
        format.json { render :show, status: :ok, location: @bread }
      else
        format.html { render :edit }
        format.json { render json: @bread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breads/1
  # DELETE /breads/1.json
  def destroy
    @bread.destroy
    respond_to do |format|
      format.html { redirect_to breads_url, notice: 'Bread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bread
      @bread = Bread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bread_params
      params.require(:bread).permit(:name, :description, :thickness_in_inches)
    end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :description, :price, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breads_helper.rb
module BreadsHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/breads/_form.html.erb
<%= form_for(@bread) do |f| %>
  <% if @bread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bread.errors.count, "error") %> prohibited this bread from being saved:</h2>

      <ul>
      <% @bread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :thickness_in_inches %><br>
    <%= f.text_field :thickness_in_inches %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breads/edit.html.erb
<h1>Editing Bread</h1>

<%= render 'form' %>

<%= link_to 'Show', @bread %> |
<%= link_to 'Back', breads_path %>

app/views/breads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Thickness in inches</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breads.each do |bread| %>
      <tr>
        <td><%= bread.name %></td>
        <td><%= bread.description %></td>
        <td><%= bread.thickness_in_inches %></td>
        <td><%= link_to 'Show', bread %></td>
        <td><%= link_to 'Edit', edit_bread_path(bread) %></td>
        <td><%= link_to 'Destroy', bread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bread', new_bread_path %>

app/views/breads/new.html.erb
<h1>New Bread</h1>

<%= render 'form' %>

<%= link_to 'Back', breads_path %>

app/views/breads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bread.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bread.description %>
</p>

<p>
  <strong>Thickness in inches:</strong>
  <%= @bread.thickness_in_inches %>
</p>

<%= link_to 'Edit', edit_bread_path(@bread) %> |
<%= link_to 'Back', breads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cafe</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pizzas/_form.html.erb
<%= form_for(@pizza) do |f| %>
  <% if @pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% @pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pizzas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizzas.each do |pizza| %>
      <tr>
        <td><%= pizza.name %></td>
        <td><%= pizza.description %></td>
        <td><%= pizza.price %></td>
        <td><%= link_to 'Show', pizza %></td>
        <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
        <td><%= link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pizza', new_pizza_path, class: "btn btn-primary" %>

app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pizza.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pizza.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pizza.price %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @pizza.photo %>
</p>
<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>